language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zxcarrot/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zxcarrot/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-059514463356"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $ACCESS_ID
  secret_access_key:
    secure: $SECRET_KEY
